version: '3.3'

services:
   db:
     image: mysql:5.7
     volumes:
       - ./data/mysql:/var/lib/mysql
     restart: ${RESTART_POLICY}
     environment:
       MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
       MYSQL_DATABASE: ${DB_NAME}
       MYSQL_USER: ${DB_USER}
       MYSQL_PASSWORD: ${DB_PASSWORD}

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - "8000:80"
     volumes:
       - ./data/wordpress:/var/www/html
       - ./floemedia_theme:/var/www/html/wp-content/themes/floemedia_theme
       #- ./my-plugin:/var/www/html/wp-content/plugins/my-plugin
     restart: ${RESTART_POLICY}
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: ${DB_USER}
       WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
       WORDPRESS_DB_NAME: ${DB_NAME}
